version: "3.7"

services:
  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: nachorand-tss_web_1
      APP_PORT: 80

  server:
    image: ertagh/teamspeak3-server
    restart: on-failure
    ports:
      - 9987:9987/udp
      - 10011:10011
      - 30033:30033
    environment:
      - TS3SERVER_LICENSE=accept
    volumes:
      - ./data/privilege-key.txt:/teamspeak/privilege-key.txt
      - ./server-command.sh:/command.sh
    command: chmod +x /command.sh && /command.sh
    healthcheck:
      test: "[ -f /teamspeak/privilege-key.txt ]"
      interval: 1s
      timeout: 10s
      retries: 600

  web:
    image: nginx:1.21-alpine@sha256:686aac2769fd6e7bab67663fd38750c135b72d993d0bb0a942ab02ef647fc9c3
    init: true
    restart: on-failure
    volumes:
      - ./data:/usr/share/nginx/html
      - ./web-command.sh:/command.sh
    command: chmod +x /command.sh && /command.sh
    depends_on:
      server:
        condition: service_healthy
