version: "3.7"

services:
  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: nachorand-tss_web_1
      APP_PORT: 8326

  server:
    image: ertagh/teamspeak3-server
    restart: always
    ports:
      - 9987:9987/udp
      - 10011:10011
      - 30033:30033
    environment:
      - TS3SERVER_LICENSE=accept
    volumes:
      - ${APP_DATA_DIR}/logs:/teamspeak/logs

  web:
    image: node:16-alpine
    user: "1000:1000"
    restart: always
    depends_on:
      - server
    volumes:
      - ${APP_DATA_DIR}/web:/app
      - ${APP_DATA_DIR}/logs:/logs
    working_dir: /app
    command: sh -c "npm install && node server.js"
    environment:
      SERVER_HOST: server
      PORT: 8326
